[project]
name = "mjlab-setup"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "mjlab",
    "pin>=3.8.0",
    "rerun-sdk>=0.20.0",
]

[tool.uv.sources]
mjlab = { path = "../mjlab", editable = true }
